# MAIN
title:               Jekyll-Susy-Starter-Kit
# description:         Jekyll-Susy-Starter-Kit description
url:                 http://localhost:3000
paginate:            1
baseurl:             /
environment:        development

# ABOUT / CONTACT
author:
  name:              S1SYPHOS
  email:             hello@daktylos.net

# MISC
version:             0.1.0
github:
  repo:              https://github.com/S1SYPHOS/Jekyll-Susy-Starter-Kit
